const labels = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const userData = {
  labels: labels,
  datasets: [
    {
      label: 'Active User',
      data: [55, 59, 73, 77, 55, 57, 50, 71, 59, 79, 77, 59],
      fill: false,
      borderColor: 'rgb(75, 192, 192)',
    },
  ],
};

export const userRows = [
  {
    id: 1,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 2,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 3,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 4,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 5,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 6,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 7,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 8,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
  {
    id: 9,
    username: 'Ali Qureshi',
    avatar: 'img.png',
    email: 'qureshi@gmail.com',
    status: 'active',
    transactions: '$1100.00',
  },
];